name: Check MicroPython syntax

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  syntax-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install linting tool (micropython-lint)
        run: |
          pip install micropython-lint

      - name: Check syntax with mpylint
        run: |
          mpylint src/
